name: Sync Remote Master to V2

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        ref: v2  # 检出目标分支

    - name: Add remote repository
      run: git remote add upstream ${{ secrets.REMOTE_REPO_URL }}

    - name: Authenticate with remote repository
      env:
        USERNAME: ${{ secrets.REMOTE_REPO_USERNAME }}
        TOKEN: ${{ secrets.REMOTE_REPO_TOKEN }}
        REPO_URL: ${{ secrets.REMOTE_REPO_URL }}
      run: git remote set-url upstream https://$USERNAME:$TOKEN@$REPO_URL

    - name: Fetch remote master branch
      run: git fetch upstream master

    - name: Reset v2 branch to match remote master
      run: git reset --hard upstream/master

    - name: Merge changes from remote master
      run: git merge upstream/master --allow-unrelated-histories

    - name: Push changes to v2 branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git v2 --force
